theme = "ayu_dark"

[editor]
line-number = "relative"
bufferline = "always"
scroll-lines = 2
soft-wrap.enable = true
file-picker.hidden = false

[editor.cursor-shape]
insert = "bar"
normal = "block"

[editor.indent-guides]
render = true
character = "‚ñè"
skip-levels = 1

[editor.statusline]
left = ["mode", "spinner", "version-control", "file-name", "file-modification-indicator"]

[keys.normal]
ret = "goto_word"
tab = ":bn"
S-tab = ":bp"

[keys.normal.space]
w = ":write"
q = ":qa"
x = ":bc"

[keys.normal.space.b]
b = ":echo %sh{git blame -L %{cursor_line},+1 %{buffer_name}}"
x = ":bc"
o = ":bco"
a = ":bca"
R = ":sh rm %{buffer_name}"
l = ":rla"
